pipeline {
    agent any
    
    environment {
        // Set the Maven home and append it to the PATH variable
        M2_HOME = "/usr/share/maven"
        PATH = "${M2_HOME}/bin:${env.PATH}"
    }
    stages {
        stage('Clone Repository') {
            steps {
                // Clone the Git repository
                git branch: 'ahmed2', url: 'https://github.com/zankech/project.git'
            }
        }
        stage('Build') {
            steps {
                // Build the project using Maven
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                // Run tests using Maven
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                // Placeholder for deployment steps
                echo 'Deploying application...'
            }
        }
    }
    post {
        success {
            // Actions to take upon success
            echo 'Pipeline succeeded!'
        }
        failure {
            // Actions to take upon failure
            echo 'Pipeline failed!'
        }
    }
}
