pipeline {
    agent any
    stages {
            stage('Checkout') {
            steps {
              git branch: 'nouhe',
              url: "https://github.com/zankech/project.git"
            }
        }

    stage('Build') {
        steps {
            dir('DevOps_Project') {
                sh 'mvn clean package'
            }
        }
    }

        }
}
 
