pipeline {
    agent any

    environment {
        M2_HOME = "usr/share/maven"
        JAVA_HOME = "/usr/lib/jvm/java-17-openjdk-amd64"
        // Ensure the PATH is set correctly without duplication
        PATH = "${M2_HOME}/bin:${JAVA_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                url: "https://github.com/zankech/5ArcTic3-Group5-Devops.git"
            }
        }

        stage('Build') {
            steps {
                dir('DevOps_Project') {
                    sh 'mvn clean package'
                }
            }
        } 
    }
} 
 
 
